# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hut', '0002_auto_20170329_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huts',
            name='image',
            field=models.ImageField(upload_to='hut/pictures'),
        ),
    ]
